name: Deploy YeOldLinkShortner
on:
  push:
    branches:
      - main
      - arm-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: server_ssh
    steps:
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "IMAGE DIGEST: $IMAGE_DIGEST"

          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/deploy_key ubuntu@54.241.201.248 "bash -s" << 'EOF'
          set -euo pipefail
          echo "Deploying YeOldLinkShortner"

          cd pe-hackathon-root

          git pull

          docker compose up --build -d

          docker image prune -f

          echo "Deployment complete!"
          EOF
